name: Tantivy_jpc

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
      - name: Install latest rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          default: true
          override: true
      - name: Build
        run: cargo build --release && mv target/release/libtantivy_jpc.so go-client/tantivy/packaged/lib/linux-amd64/ && cp -u target/tantivy_jpc.h go-client/tantivy/packaged/include/
      - name: Run tests
        run: cargo test --verbose
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: update linux binary
          title: Update libtantivy_jpc.so
          body: Credit new contributors by updating libtantivy_jpc.so
          branch: update-linux-binary
          delete-branch: true
          base: master
  build-mac:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install latest rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          target: x86_64-apple-darwin
          default: true
          override: true

      - name: Build for mac
        run: cargo build --release && mv target/release/libtantivy_jpc.dylib go-client/tantivy/packaged/lib/darwin-amd64/

      - name: Run tests
        run: cargo test --verbose

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: update darwin binary
          title: Update libtantivy_jpc.dylib
          body: Credit new contributors by updating libtantivy_jpc.dylib
          branch: update-darwin-binary
          delete-branch: true
          base: master
